#!/bin/sh

if git diff --cached --name-only | grep '^src/'
then
  if ! yarn lint
  then
    echo Commit canceled: lint failed.
    exit 1
  fi
fi

if [[ $(git diff --cached --name-only -w -G'(^[^\*# /])|(^#\w)|(^\s+[^\*#/])' | grep '^src/') || $(git diff --cached --name-only | grep '^test/') ]]
then
  if ! yarn test:report
  then
    echo Commit canceled: test failed.
    exit 1
  fi
fi

if git diff --cached --name-only -w -G'(^[^\*# /])|(^#\w)|(^\s+[^\*#/])' | grep '^src/.*\|rollup\.config\.js$'
then
  if ! yarn build
  then
    echo Commit canceled: build failed.
    exit 1
  fi
  git add dist
fi

if git diff --cached --name-only | grep '^src/.*\|tutorials/.*\|README\.md|jsdoc\.config\.json$'
then
  if ! yarn docs
  then
    echo Commit canceled: docs failed.
    exit 1
  fi
  git add docs
fi
